LNAME = YOONHA
LNAME = KIM
FNAME = CHULSOO

LNAME += MANSOO

NAME = '"KWON PARK"'

A = $(B) AA
B = BB

a := $(b) aa
b := bb

all :
	@echo ${LNAME}
	@echo A= $(A)
	@echo a= $(a)
	@echo LNAME= $(LNAME)
	@echo ${LNAME}, $(FNAME)
	@echo Mr. $(LNAME)
